const domProps = require('uglify-js/tools/domprops.json')

module.exports = domProps
  .concat([
    // '__dynC',
    // 'style',
    // 'className',
    // 'children',
    // 'set',
    // 'get',
    // 'value',
    // 'state',
    // 'props',
    'regeneratorRuntime',
    'SimpleEventPlugin',
    'EnterLeaveEventPlugin',
    'ChangeEventPlugin',
    'SelectEventPlugin',
    'BeforeInputEventPlugin',
    'ResponderEventPlugin',
    'ReactNativeBridgeEventPlugin'
  ])
  .concat([
    // 'Children',
    // 'createRef',
    // 'Component',
    // 'PureComponent',
    // 'createContext',
    // 'forwardRef',
    // 'Fragment',
    // 'StrictMode',
    // 'unstable_AsyncMode',
    // 'createElement',
    // 'cloneElement'
    // 'createFactory',
    // 'isValidElement',
    // 'version',
    // '__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED'
  ])
  .concat([
    // 'EventPluginHub',
    // 'injection',
    // 'injectEventPluginOrder',
    // 'injectEventPluginsByName',
    // 'getListener',
    // 'runEventsInBatch',
    // 'runExtractedEventsInBatch',
    // 'EventPluginRegistry',
    // 'plugins',
    // 'eventTypes',
    'blur',
    'phasedRegistrationNames',
    'bubbled',
    'onBlur',
    'captured',
    'onBlurCapture',
    'dependencies',
    'topBlur',
    'isInteractive',
    'cancel',
    'onCancel',
    'onCancelCapture',
    'topCancel',
    'click',
    'onClick',
    'onClickCapture',
    'topClick',
    'close',
    'onClose',
    'onCloseCapture',
    'topClose',
    'contextMenu',
    'onContextMenu',
    'onContextMenuCapture',
    'topContextMenu',
    'copy',
    'onCopy',
    'onCopyCapture',
    'topCopy',
    'cut',
    'onCut',
    'onCutCapture',
    'topCut',
    'doubleClick',
    'onDoubleClick',
    'onDoubleClickCapture',
    'topDoubleClick',
    'dragEnd',
    'onDragEnd',
    'onDragEndCapture',
    'topDragEnd',
    'dragStart',
    'onDragStart',
    'onDragStartCapture',
    'topDragStart',
    'drop',
    'onDrop',
    'onDropCapture',
    'topDrop',
    'focus',
    'onFocus',
    'onFocusCapture',
    'topFocus',
    'input',
    'onInput',
    'onInputCapture',
    'topInput',
    'invalid',
    'onInvalid',
    'onInvalidCapture',
    'topInvalid',
    'keyDown',
    'onKeyDown',
    'onKeyDownCapture',
    'topKeyDown',
    'keyPress',
    'onKeyPress',
    'onKeyPressCapture',
    'topKeyPress',
    'keyUp',
    'onKeyUp',
    'onKeyUpCapture',
    'topKeyUp',
    'mouseDown',
    'onMouseDown',
    'onMouseDownCapture',
    'topMouseDown',
    'mouseUp',
    'onMouseUp',
    'onMouseUpCapture',
    'topMouseUp',
    'paste',
    'onPaste',
    'onPasteCapture',
    'topPaste',
    'pause',
    'onPause',
    'onPauseCapture',
    'topPause',
    'play',
    'onPlay',
    'onPlayCapture',
    'topPlay',
    'rateChange',
    'onRateChange',
    'onRateChangeCapture',
    'topRateChange',
    'reset',
    'onReset',
    'onResetCapture',
    'topReset',
    'seeked',
    'onSeeked',
    'onSeekedCapture',
    'topSeeked',
    'submit',
    'onSubmit',
    'onSubmitCapture',
    'topSubmit',
    'touchCancel',
    'onTouchCancel',
    'onTouchCancelCapture',
    'topTouchCancel',
    'touchEnd',
    'onTouchEnd',
    'onTouchEndCapture',
    'topTouchEnd',
    'touchStart',
    'onTouchStart',
    'onTouchStartCapture',
    'topTouchStart',
    'volumeChange',
    'onVolumeChange',
    'onVolumeChangeCapture',
    'topVolumeChange',
    'abort',
    'onAbort',
    'onAbortCapture',
    'topAbort',
    'animationEnd',
    'onAnimationEnd',
    'onAnimationEndCapture',
    'topAnimationEnd',
    'animationIteration',
    'onAnimationIteration',
    'onAnimationIterationCapture',
    'topAnimationIteration',
    'animationStart',
    'onAnimationStart',
    'onAnimationStartCapture',
    'topAnimationStart',
    'canPlay',
    'onCanPlay',
    'onCanPlayCapture',
    'topCanPlay',
    'canPlayThrough',
    'onCanPlayThrough',
    'onCanPlayThroughCapture',
    'topCanPlayThrough',
    'drag',
    'onDrag',
    'onDragCapture',
    'topDrag',
    'dragEnter',
    'onDragEnter',
    'onDragEnterCapture',
    'topDragEnter',
    'dragExit',
    'onDragExit',
    'onDragExitCapture',
    'topDragExit',
    'dragLeave',
    'onDragLeave',
    'onDragLeaveCapture',
    'topDragLeave',
    'dragOver',
    'onDragOver',
    'onDragOverCapture',
    'topDragOver',
    'durationChange',
    'onDurationChange',
    'onDurationChangeCapture',
    'topDurationChange',
    'emptied',
    'onEmptied',
    'onEmptiedCapture',
    'topEmptied',
    'encrypted',
    'onEncrypted',
    'onEncryptedCapture',
    'topEncrypted',
    'ended',
    'onEnded',
    'onEndedCapture',
    'topEnded',
    'error',
    'onError',
    'onErrorCapture',
    'topError',
    'load',
    'onLoad',
    'onLoadCapture',
    'topLoad',
    'loadedData',
    'onLoadedData',
    'onLoadedDataCapture',
    'topLoadedData',
    'loadedMetadata',
    'onLoadedMetadata',
    'onLoadedMetadataCapture',
    'topLoadedMetadata',
    'loadStart',
    'onLoadStart',
    'onLoadStartCapture',
    'topLoadStart',
    'mouseMove',
    'onMouseMove',
    'onMouseMoveCapture',
    'topMouseMove',
    'mouseOut',
    'onMouseOut',
    'onMouseOutCapture',
    'topMouseOut',
    'mouseOver',
    'onMouseOver',
    'onMouseOverCapture',
    'topMouseOver',
    'playing',
    'onPlaying',
    'onPlayingCapture',
    'topPlaying',
    'progress',
    'onProgress',
    'onProgressCapture',
    'topProgress',
    'scroll',
    'onScroll',
    'onScrollCapture',
    'topScroll',
    'seeking',
    'onSeeking',
    'onSeekingCapture',
    'topSeeking',
    'stalled',
    'onStalled',
    'onStalledCapture',
    'topStalled',
    'suspend',
    'onSuspend',
    'onSuspendCapture',
    'topSuspend',
    'timeUpdate',
    'onTimeUpdate',
    'onTimeUpdateCapture',
    'topTimeUpdate',
    'toggle',
    'onToggle',
    'onToggleCapture',
    'topToggle',
    'touchMove',
    'onTouchMove',
    'onTouchMoveCapture',
    'topTouchMove',
    'transitionEnd',
    'onTransitionEnd',
    'onTransitionEndCapture',
    'topTransitionEnd',
    'waiting',
    'onWaiting',
    'onWaitingCapture',
    'topWaiting',
    'wheel',
    'onWheel',
    'onWheelCapture',
    'topWheel',
    'isInteractiveTopLevelEventType',
    'extractEvents',
    'mouseEnter',
    'registrationName',
    'onMouseEnter',
    'mouseLeave',
    'onMouseLeave',
    'change',
    'onChange',
    'onChangeCapture',
    'topChange',
    'topSelectionChange',
    '_isInputEventSupported',
    'select',
    'onSelect',
    'onSelectCapture',
    'beforeInput',
    'onBeforeInput',
    'onBeforeInputCapture',
    'topCompositionEnd',
    'topTextInput',
    'compositionEnd',
    'onCompositionEnd',
    'onCompositionEndCapture',
    'compositionStart',
    'onCompositionStart',
    'onCompositionStartCapture',
    'topCompositionStart',
    'compositionUpdate',
    'onCompositionUpdate',
    'onCompositionUpdateCapture',
    'topCompositionUpdate',
    'eventNameDispatchConfigs',
    'registrationNameModules',
    'registrationNameDependencies',
    'possibleRegistrationNames',
    'onblur',
    'onblurcapture',
    'oncancel',
    'oncancelcapture',
    'onclick',
    'onclickcapture',
    'onclose',
    'onclosecapture',
    'oncontextmenu',
    'oncontextmenucapture',
    'oncopy',
    'oncopycapture',
    'oncut',
    'oncutcapture',
    'ondoubleclick',
    'ondblclick',
    'ondoubleclickcapture',
    'ondragend',
    'ondragendcapture',
    'ondragstart',
    'ondragstartcapture',
    'ondrop',
    'ondropcapture',
    'onfocus',
    'onfocuscapture',
    'oninput',
    'oninputcapture',
    'oninvalid',
    'oninvalidcapture',
    'onkeydown',
    'onkeydowncapture',
    'onkeypress',
    'onkeypresscapture',
    'onkeyup',
    'onkeyupcapture',
    'onmousedown',
    'onmousedowncapture',
    'onmouseup',
    'onmouseupcapture',
    'onpaste',
    'onpastecapture',
    'onpause',
    'onpausecapture',
    'onplay',
    'onplaycapture',
    'onratechange',
    'onratechangecapture',
    'onreset',
    'onresetcapture',
    'onseeked',
    'onseekedcapture',
    'onsubmit',
    'onsubmitcapture',
    'ontouchcancel',
    'ontouchcancelcapture',
    'ontouchend',
    'ontouchendcapture',
    'ontouchstart',
    'ontouchstartcapture',
    'onvolumechange',
    'onvolumechangecapture',
    'onabort',
    'onabortcapture',
    'onanimationend',
    'onanimationendcapture',
    'onanimationiteration',
    'onanimationiterationcapture',
    'onanimationstart',
    'onanimationstartcapture',
    'oncanplay',
    'oncanplaycapture',
    'oncanplaythrough',
    'oncanplaythroughcapture',
    'ondrag',
    'ondragcapture',
    'ondragenter',
    'ondragentercapture',
    'ondragexit',
    'ondragexitcapture',
    'ondragleave',
    'ondragleavecapture',
    'ondragover',
    'ondragovercapture',
    'ondurationchange',
    'ondurationchangecapture',
    'onemptied',
    'onemptiedcapture',
    'onencrypted',
    'onencryptedcapture',
    'onended',
    'onendedcapture',
    'onerror',
    'onerrorcapture',
    'onload',
    'onloadcapture',
    'onloadeddata',
    'onloadeddatacapture',
    'onloadedmetadata',
    'onloadedmetadatacapture',
    'onloadstart',
    'onloadstartcapture',
    'onmousemove',
    'onmousemovecapture',
    'onmouseout',
    'onmouseoutcapture',
    'onmouseover',
    'onmouseovercapture',
    'onplaying',
    'onplayingcapture',
    'onprogress',
    'onprogresscapture',
    'onscroll',
    'onscrollcapture',
    'onseeking',
    'onseekingcapture',
    'onstalled',
    'onstalledcapture',
    'onsuspend',
    'onsuspendcapture',
    'ontimeupdate',
    'ontimeupdatecapture',
    'ontoggle',
    'ontogglecapture',
    'ontouchmove',
    'ontouchmovecapture',
    'ontransitionend',
    'ontransitionendcapture',
    'onwaiting',
    'onwaitingcapture',
    'onwheel',
    'onwheelcapture',
    'onmouseenter',
    'onmouseleave',
    'onchange',
    'onchangecapture',
    'onselect',
    'onselectcapture',
    'onbeforeinput',
    'onbeforeinputcapture',
    'oncompositionend',
    'oncompositionendcapture',
    'oncompositionstart',
    'oncompositionstartcapture',
    'oncompositionupdate',
    'oncompositionupdatecapture'
    // 'EventPropagators',
    // 'accumulateTwoPhaseDispatches',
    // 'accumulateTwoPhaseDispatchesSkipTarget',
    // 'accumulateEnterLeaveDispatches',
    // 'accumulateDirectDispatches',
    // 'ReactControlledComponent',
    // 'injectFiberControlledHostComponent',
    // 'enqueueStateRestore',
    // 'needsStateRestore',
    // 'restoreStateIfNeeded',
    // 'ReactDOMComponentTree',
    // 'precacheFiberNode',
    // 'getClosestInstanceFromNode',
    // 'getInstanceFromNode',
    // 'getNodeFromInstance',
    // 'getFiberCurrentPropsFromNode',
    // 'updateFiberProps',
    // 'ReactDOMEventListener',
    // '_enabled',
    // 'setEnabled',
    // 'isEnabled',
    // 'trapBubbledEvent',
    // 'trapCapturedEvent',
    // 'dispatchEvent'
  ])
