const BOTTOMBAR_HEIGHT = 30
const LIST_WIDTH = 250
const MAX_CONTENT_WIDTH = 1000
const CONTENT_WIDTH = 600
const MIN_CONTENT_WIDTH = 300

export {
  BOTTOMBAR_HEIGHT,
  LIST_WIDTH,
  MAX_CONTENT_WIDTH,
  CONTENT_WIDTH,
  MIN_CONTENT_WIDTH
}
